name: word_pronunciation
description: "word pronunciation app"
publish_to: 'none'
version: 1.0.0
homepage: https://github.com/shizopudge/word-pronunciation
repository: https://github.com/shizopudge/word-pronunciation

platforms:
  android:
  ios:

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # Widgets
  smooth_page_indicator: ^1.1.0
  avatar_glow: ^3.0.1

  # Network
  dio: ^5.4.0

  # Equatable
  equatable: ^2.0.5

  # Localizations & Intl
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Firebase
  firebase_analytics: ^10.7.0
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4

  # State management
  flutter_bloc: ^8.1.3

  # Utils
  speech_to_text: ^6.4.1
  flutter_svg: ^2.0.9
  just_audio: ^0.9.36
  lottie: ^3.0.0
  permission_handler: ^11.3.0
  path: ^1.8.3

  # Check Connect status
  connectivity_plus: ^4.0.2

  # Annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Logger
  logger: ^2.0.2+1

  # Local key value storage
  shared_preferences: ^2.2.2

  # SDK extensions
  collection: ^1.17.1
  meta: ^1.9.1

  # DB
  sqflite: ^2.3.2

  # RxDart
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.1
  flutter_native_splash: ^2.3.10

flutter_gen:
  output: lib/src/core/resources/src
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

flutter:
  # Enable generation of localized Strings from arb files.
  generate: true
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        # Extra Bold
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        # Extra Bold Italic
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        # Bold
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        # Bold Italic
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic
        # Semibold
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        # Semibold Italic
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        # Medium
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        # Medium Italic
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
          weight: 500
          style: italic
        # Regular
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        # Light
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        # Light Italic
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
          weight: 300
          style: italic
        # Ultralight
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        # Ultralight Italic
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
          weight: 200
          style: italic

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#000000"
  image_dark: assets/images/logo_dark.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/logo_dark.png
    icon_background_color_dark: "#000000"

  web: false